name: Update Prices

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Test Bitpin TON
        run: |
          curl -L -s "https://api.bitpin.ir/v1/mkt/markets/" | node -e "
          let data='';
          process.stdin.on('data',c=>data+=c);
          process.stdin.on('end',()=>{
            let json=JSON.parse(data);

            let markets = json.results.filter(x =>
              JSON.stringify(x).toUpperCase().includes('TON')
            );

            console.log(JSON.stringify(markets.map(x => ({
              code:x.code,
              title:x.title,
              price:x.price
            })), null, 2));
          });
          "
